version: '3.7'

services:

  backend:
    build:
      context: ./backend
    container_name: django_backend
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./frontend
    container_name: nuxt_frontend
    # This section allows for hot reloading for some contributors but is a breaking change for others
    # See: https://github.com/activist-org/activist/issues/55
    # volumes:
    #   - ./frontend:/app
    ports:
      - "3000:3000"
