name: welcome

on: [issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: "## Welcome!\nThanks so much for opening your first issue :) This bot's here to let you know we'll be with you as soon as we can.\n\nBest regards,\nThe activist.org Team"
